annotation  ::= '@'(namespace|)(identifier) ((type |) value |)
identifier  ::= '[a-z] [A-Z] [0-9] _ -'
namespace   ::= (delimiter|)(identifier(delimiter))+
delimiter   ::= '.' | '\'
type        ::= 'json' | 'string' | 'integer' | 'float' | '->'
value       ::= 'any unicode characters including \n'
